import { chromium } from 'playwright';
const browser = await chromium.connectOverCDP('http://127.0.0.1:9333');
const ctx = browser.contexts()[0];
const page = ctx.pages()[0];
await page.waitForLoadState('domcontentloaded');
console.log('URL:', page.url());
await page.waitForTimeout(1500);
await page.screenshot({ path: '/private/tmp/claude-501/-Users-danielluan-Desktop-3D-Nash-Equilibrium/5d5d682e-2a27-4687-ac2f-801e07672846/scratchpad/rd6_before_save.png' });
console.log('screenshot before save taken');
await browser.close();
