/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * The pre-verified scenario bank — what the desktop shows instead of running a
 * model.
 *
 * WHY A BANK AT ALL. The retrained local 0.6B is excellent on every decidable
 * axis (six-screen defects 5%, gate rejection 1.0%, 1.35s) and still writes an
 * incoherent world about a quarter of the time — a rice farmer with a saffron
 * crop, a coffee roastery that harvests its own beans. That class is invisible
 * to every screen we ship: 178 of 178 defective stories passed all three gates.
 * And it cannot be trained out from here, because the teacher corpus IS cloud
 * output and cloud is 0% defective — the incoherence is generated by the small
 * model, not inherited, so no retrain on cleaner data addresses it.
 *
 * Measured head to head, blind, criteria sealed before generation and picks
 * sealed before the key, paired on identical (game, domain):
 *
 *     bank   0/68 defective        model   25% defective     p = 6.1e-5
 *
 * WHY THIS IS NOT A CHEAT. At rung 3 the story is MEASURABLY independent of the
 * game: an all-zero matrix produces stories indistinguishable from real ones
 * (p=0.115), and varying the game moves output no more than resampling the same
 * game does (p=0.238). That is by design — the solver states every number, so
 * the description is forbidden to. The one property that does depend on the
 * game is the STAKES BAND, and that is what the bank is indexed on. Selection
 * therefore delivers exactly what generation delivered, minus the incoherence.
 *
 * It also costs less: no model in the installer (~378 MB saved) and no
 * inference at display time.
 */
import type { GamePayoffs, SuggestedScenario } from '../types';
import { describeStakes } from './scenarioStakes';

export interface BankEntry {
  /** 0 tiny · 1 modest · 2 substantial · 3 very large — the stakes band. */
  b: number;
  /** The rotation setting this story was written for. */
  d: string;
  s: SuggestedScenario;
}

/** The four bands, matching `stakesHint`'s cuts exactly. */
export function stakesBand(g: GamePayoffs): number {
  const swing = describeStakes(g).swing;
  return swing < 1 ? 0 : swing < 10 ? 1 : swing < 50 ? 2 : 3;
}

/**
 * SOFT STAKES for the bank (2026-09-02, same ruling as `stakesHint`'s
 * `SIZE_STRONG_P`/`blendedSizeBand` — see that file's comment for the full
 * argument: payoff scale should INFLUENCE which story gets served, not
 * DETERMINE it). Every bank row was written for an EXACT band at generation
 * time, so unlike the prompt hint there is no "say nothing" option here — the
 * only lever is WHICH band to draw from, so this reaches one band over,
 * sometimes, instead of always the exact one.
 *
 * DELIBERATELY NEVER TWO BANDS OVER: a tiny game served a very-large row would
 * contradict the numbers on screen as badly as the thing `pickFromBank`'s own
 * WIDENING LADDER treats as a last resort, not a first choice. Reaching one
 * band over is the discrete-artifact version of the boundary blend below —
 * "9.5 next to a cut at 10 is not a different decision" — not a general
 * license to serve any register to any game.
 *
 * Applied BEFORE the widening ladder, not as a substitute for it: a softened
 * target band that turns out to be empty for this (domain, seen) still widens
 * through the same four tiers, using the softened band as tier 1/2's `band`.
 */
const BAND_NEIGHBOR_P = 0.3;

function softenBand(exact: number, pick: () => number): number {
  if (pick() >= BAND_NEIGHBOR_P) return exact;
  const neighbors = [exact - 1, exact + 1].filter((b) => b >= 0 && b <= 3);
  if (!neighbors.length) return exact;
  return neighbors.length === 1 ? neighbors[0] : (pick() < 0.5 ? neighbors[0] : neighbors[1]);
}

/**
 * Pick a story for this game, WITHOUT REPLACEMENT within a session.
 *
 * The naive picker — uniform with replacement inside a cell — returns a
 * previously seen story 20.6% of the time on the second draw and 50.7% on the
 * third, and a previously seen NAME 44.8% of the time, because 214 of 314 cells
 * hold at least two stories sharing a title. The prose underneath is genuinely
 * different (6 of 3,678 within-cell pairs above Jaccard 0.5, none above 0.7),
 * so this is a naming problem rather than a content one — but a reader meeting
 * "Harbour Inspection" three times will not care about the distinction.
 *
 * WHY "WITHOUT REPLACEMENT" DID NOT HOLD IN PRACTICE, and the fix. The tiers
 * below only ever looked INSIDE one pool, and the pool was the exact
 * (domain, band) cell whenever that cell was non-empty. 34 of 320 cells in the
 * shipped artifact hold exactly ONE distinct name — "lighthouse relief shifts"
 * band 2 is eight rows all titled "Lighthouse Relief Shifts" — so the moment
 * that title was shown, every remaining row in the cell fell to the last tier
 * and the title came back. Measured on the shipped bank with the domain held
 * fixed, which is the condition that isolates the defect: repeated-title rate
 * 29.5% at 5 presses, 60.7% at 10, 80.3% at 20, 90.2% at 40.
 *
 * So a cell that cannot offer an unseen NAME now WIDENS rather than repeating.
 *
 * THE WIDENING LADDER, and why it is ordered this way. The two things a widened
 * pick can lose are the stakes register and the setting:
 *
 *   1. the exact cell — (domain, band)
 *   2. THE SAME BAND, any domain
 *   3. the same domain, any band
 *   4. anything at all
 *
 * Band before domain, because the band is derived from the USER'S OWN MATRIX
 * while the domain is a rotation choice the user never made and cannot see the
 * absence of. A story from the wrong band contradicts the numbers printed
 * beside it — "a modest patch of coppice" against a swing of 120 — which is a
 * mismatch a reader can detect; a story from a different setting is simply a
 * different setting. (This also fixes the reverse defect: an EMPTY exact cell
 * used to widen by DOMAIN first, so a band-3 game in a domain whose band-3 cell
 * was empty was served that domain's band-0 story.)
 *
 * `seen` is the caller's session memory. Note that an unseen NAME implies an
 * unseen ENTRY — `seenNames` is derived from `seen` — so the old middle tier
 * ("unseen name, seen entry") was unreachable and is gone rather than left
 * standing as a check that cannot fire.
 */
export function pickFromBank(
  bank: BankEntry[],
  g: GamePayoffs,
  domain: string,
  seen: ReadonlySet<string>,
  pick: () => number = Math.random,
): SuggestedScenario | null {
  const band = softenBand(stakesBand(g), pick);
  const ladder: BankEntry[][] = [
    bank.filter((e) => e.d === domain && e.b === band),
    bank.filter((e) => e.b === band),
    bank.filter((e) => e.d === domain),
    bank,
  ];
  const seenNames = new Set([...seen].map((k) => k.split('|')[1]));
  const take = (pool: BankEntry[]) => pool[Math.min(Math.floor(pick() * pool.length), pool.length - 1)].s;

  // A name the reader has not met, as close to the exact cell as one exists.
  for (const pool of ladder) {
    const fresh = pool.filter((e) => !seenNames.has(e.s.name ?? ''));
    if (fresh.length) return take(fresh);
  }
  // Every name in the bank has been shown. Repeating a title is now the honest
  // outcome; at least give the reader prose they have not read.
  for (const pool of ladder) {
    const unseen = pool.filter((e) => !seen.has(bankKey(e)));
    if (unseen.length) return take(unseen);
  }
  for (const pool of ladder) if (pool.length) return take(pool);
  return null;
}

/** The session key for an entry the caller has shown. */
export function bankKey(e: BankEntry): string {
  return `${e.d}|${e.s.name}|${(e.s.description ?? '').slice(0, 40)}`;
}

/**
 * THE GAMES A BANK ROW MUST SURVIVE — the serving condition, written down.
 *
 * `_gen/bank_build.ts` gates each row against the game it was GENERATED for.
 * `pickFromBank` then serves it with the game the USER typed. Every
 * game-dependent rule in `validateScenario` therefore gets a different answer at
 * serve time than it did at build time, and a row can be admitted to the bank
 * and rejected in front of a reader — where the desktop has no model to fall
 * back to and, measured through the real path, the response silently carries no
 * story at all.
 *
 * That is not hypothetical. 19 shipped rows carry rivalry vocabulary ("competing
 * for", "are rivals") and `validateScenario` rejects those on any COMMON-INTEREST
 * matrix, which is the plain pure-coordination game and also the all-zero matrix
 * a user gets by clearing the payoff fields. Reproduced independently by two
 * agents from opposite directions — a 270-game probe sweep and a
 * one-probe-per-conditional-branch sweep — and both found the same 19 and only
 * those 19.
 *
 * So a row must survive EVERY shape it can be served with, and this is that set:
 * one entry per condition the gates actually branch on, read off the code rather
 * than guessed, at three magnitudes because `stakesBand` and the near-tolerances
 * are scale-dependent.
 *
 * NOT BAND-SCOPED, DELIBERATELY. `pickFromBank`'s ladder is band-locked at tiers
 * 1 and 2, so a band-0 game cannot reach a band-3 row until every band-0 name is
 * exhausted — which means an incidence measured on one band says nothing about
 * another (the same 19 rows are 1.50% of presses on a band-3 common-interest
 * game and 0.00% on a band-0 one). Reachability is what matters here, not
 * incidence: tiers 3 and 4 mean ANY row can eventually be served for ANY game,
 * so the screen must ignore bands entirely. Do not "optimise" this by matching
 * the probe's band to the row's.
 *
 * AND A WARNING ABOUT ITS ZEROS. Most of these shapes currently return zero
 * rejections, and that is NOT evidence the artifact is safe on them — it is
 * evidence the corpus never says the things those rules look for
 * (`SHARED_GOAL`, `ABSTRACT_COORD`, `COORD_TALK`, `ANTI_TALK` and `DETERMINES`
 * all have zero vocabulary presence in the bank). The probes earn their keep the
 * day a generation run or a narrowed screen lets that vocabulary back in.
 */
export const SERVE_PROBES: GamePayoffs[] = (() => {
  const shapes: Array<(k: number) => GamePayoffs> = [
    // common interest — both payoffs identical in every cell (rivalry rule)
    (k) => ({ a11: 9 * k, a12: -4 * k, a21: -4 * k, a22: 7 * k, b11: 9 * k, b12: -4 * k, b21: -4 * k, b22: 7 * k }),
    // constant sum, NON-zero total (shared-goal rule) — every cell sums to 10k.
    // A zero total would be the zero-sum shape below rather than a distinct one.
    (k) => ({ a11: 3 * k, a12: -2 * k, a21: -4 * k, a22: 5 * k, b11: 7 * k, b12: 12 * k, b21: 14 * k, b22: 5 * k }),
    // zero sum on the matching diagonal
    (k) => ({ a11: 2 * k, a12: -2 * k, a21: -2 * k, a22: 2 * k, b11: -2 * k, b12: 2 * k, b21: 2 * k, b22: -2 * k }),
    // A indifferent between its OWN actions: a11 === a21 and a12 === a22, so
    // A's two rows pay the same against either column and a whole line is in
    // equilibrium. B stays strict, so exactly one player is indifferent.
    (k) => ({ a11: 5 * k, a12: 2 * k, a21: 5 * k, a22: 2 * k, b11: 1 * k, b12: 4 * k, b21: 3 * k, b22: 0 }),
    // B indifferent between its OWN actions: b11 === b12 and b21 === b22.
    (k) => ({ a11: 1 * k, a12: 4 * k, a21: 3 * k, a22: 0, b11: 5 * k, b12: 5 * k, b21: 2 * k, b22: 2 * k }),
    // dominance for both (dependence-framing rules)
    (k) => ({ a11: 3 * k, a12: 0, a21: 5 * k, a22: 1 * k, b11: 3 * k, b12: 5 * k, b21: 0, b22: 1 * k }),
    // pure equilibria on MATCHING pairs (coordination direction check)
    (k) => ({ a11: 4 * k, a12: 0, a21: 0, a22: 3 * k, b11: 3 * k, b12: 0, b21: 0, b22: 4 * k }),
    // pure equilibria on MISMATCHED pairs (anti-coordination direction check)
    (k) => ({ a11: 0, a12: 4 * k, a21: 3 * k, a22: 0, b11: 0, b12: 3 * k, b21: 4 * k, b22: 0 }),
    // no pure equilibrium at all
    (k) => ({ a11: 2 * k, a12: -1 * k, a21: -1 * k, a22: 1 * k, b11: -2 * k, b12: 1 * k, b21: 1 * k, b22: -1 * k }),
  ];
  const out: GamePayoffs[] = shapes.flatMap((f) => [f(0.1), f(1), f(20)]);
  // BOTH players indifferent — the all-zero matrix a user gets by clearing every
  // field. Scale-free, so it is added once rather than three times.
  out.push({ a11: 0, a12: 0, a21: 0, a22: 0, b11: 0, b12: 0, b21: 0, b22: 0 });
  return out;
})();

/**
 * Whether a scenario's actorA/actorB nouns are safe to ship for colour
 * labelling (BLUE-NOUNS-8 phase 3, 2026-09-03: bank backfill via
 * deepseek-v4-flash/OpenRouter, `_gen/bank_actor_nouns.ts`).
 *
 * Shared between the backfill harness (decides which extraction to keep) and
 * `src/scenariobank.test.ts` (re-screens the SHIPPED artifact) so the two can
 * never silently disagree about what counts as a safe noun — the same failure
 * class this file's own header warns about for the story gates themselves.
 *
 * A row that declares NOTHING (both null/empty) always passes: silence is
 * always safe, and the caller decides separately whether nouns are required.
 * A row that declares something must clear every bar:
 *   - each entry is a VERBATIM substring of the description (NFKC-normalized,
 *     zero-width-stripped, case-insensitive — the same normalization
 *     `colorTerms.ts`'s `dropAmbiguous` uses, so this and the eventual
 *     highlighter agree on what "the same text" means);
 *   - at most 3 entries per player;
 *   - the two players' lists are DISJOINT (no phrase claimed by both);
 *   - no entry equals any of the four option labels (a noun cannot also be
 *     an option name — that is a `dropAmbiguous`-shaped collision, not a
 *     valid actor noun).
 * Any violation fails the WHOLE row, deliberately — this project does not
 * partially repair model output; a row that fails gets NO nouns, not a
 * best-effort trim (see CLAUDE.md's `no-rewriting-rung3-ceiling`).
 */
export function actorNounsOk(sc: {
  actorA?: unknown; actorB?: unknown; description?: string | null;
  row1?: string | null; row2?: string | null; col1?: string | null; col2?: string | null;
}): boolean {
  const a = Array.isArray(sc.actorA) ? sc.actorA : sc.actorA == null ? [] : null;
  const b = Array.isArray(sc.actorB) ? sc.actorB : sc.actorB == null ? [] : null;
  if (a === null || b === null) return false; // malformed shape, not merely empty
  if (a.length === 0 && b.length === 0) return true;
  if (a.length > 3 || b.length > 3) return false;
  if (!a.every((t) => typeof t === 'string') || !b.every((t) => typeof t === 'string')) return false;
  const norm = (t: string) => t
    .normalize('NFKC')
    .replace(/[​-‍﻿]/g, '')
    .trim()
    .toLowerCase();
  const descNorm = norm(sc.description ?? '');
  const all = [...(a as string[]), ...(b as string[])];
  // Same floor `cleanUserColorTerms` (colorTerms.ts) uses for a user-typed
  // term: a single character is indistinguishable from an article ("a") and
  // would highlight (or here, verbatim-match) almost any description.
  // Length checked AFTER normalization, not on the raw string: a zero-width
  // character (e.g. U+200B) survives `.trim()` (it is not whitespace) but is
  // stripped by `norm`, so "​a" reads as 2 raw characters and 1 real
  // one — checking the raw length would let a single-character noun through
  // the same floor `cleanUserColorTerms` enforces (CodeRabbit, phase 3 review).
  if (all.some((t) => { const n = norm(t); return n.length < 2 || !descNorm.includes(n); })) return false;
  // LITERAL-SUBSTRING GUARD (RED-REGEN-2/001, 2026-09-04). The check above is
  // NORMALIZED (NFKC + zero-width-stripped) — a noun that clears it only via
  // normalization (a zero-width space spliced into "farmer", or fullwidth
  // Latin "Ａ ｇｒａｉｎ ｔｒａｄｅｒ") is not a byte-for-byte substring of the
  // description. `ColorCoded.tsx` builds its highlight regex from the RAW,
  // unnormalized term against the RAW, unnormalized description text (only
  // regex metacharacters escaped, word-boundary lookarounds, `gi` flags, no
  // `.normalize()` anywhere) — so a noun that passes only the normalized
  // check above can never actually highlight, silently, even though the
  // server calls it "verbatim" and lets it ship as a colour-term chip.
  //
  // Reuse that EXACT predicate, not a hand-rolled `.toLowerCase().includes()`
  // (CodeRabbit review): the two are not equivalent. `.toLowerCase()` folds
  // U+212A KELVIN SIGN to ASCII "k" (`'K'.toLowerCase() === 'k'`), but a
  // plain `gi`-flagged regex (no `u` flag, exactly what ColorCoded.tsx uses)
  // does NOT fold it (`/k/i.test('K')` is false) — so a noun containing
  // the Kelvin sign could pass an `.includes()`-based check against an
  // ordinary "kelvin" in the description while still never matching the
  // real highlighter's regex, reopening the exact defect this guard exists
  // to close. A plain substring check also ignores the highlighter's
  // word-boundary lookarounds, so it would accept "vendor" as verbatim
  // inside "prevendors" (no word boundary there) even though the real regex
  // never matches it. Building the identical regex here makes this
  // predicate and the highlighter's decision provably the same by
  // construction, not merely similar — which is also why the term is used
  // RAW, not `.trim()`'d (CodeRabbit, this review): `ColorCoded.tsx` builds
  // its own regex from the entry's term exactly as stored, with no trim, so
  // a noun carrying incidental leading/trailing whitespace would highlight
  // (or fail to) based on that literal whitespace too — trimming here would
  // accept a whitespace-padded noun this predicate is supposed to reject,
  // because the real regex's word-boundary lookarounds see the space
  // character as part of the match, not the caller's convenience trim.
  const escapeForRegex = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const highlightWouldMatch = (term: string, desc: string) => {
    if (!term) return false;
    const re = new RegExp(`(?<![\\w])(?:${escapeForRegex(term)})(?![\\w])`, 'gi');
    return re.test(desc);
  };
  const rawDesc = sc.description ?? '';
  if (all.some((t) => !highlightWouldMatch(t, rawDesc))) return false;
  const aSet = new Set((a as string[]).map(norm));
  const bSet = new Set((b as string[]).map(norm));
  if ([...aSet].some((t) => bSet.has(t))) return false;
  const labels = [sc.row1, sc.row2, sc.col1, sc.col2]
    .filter((t): t is string => typeof t === 'string' && t.length > 0)
    .map(norm);
  if (all.some((t) => labels.includes(norm(t)))) return false;
  // A NOUN NAMES ONE ENTITY. Found hand-reading the phase-3 bank backfill
  // (BLUE-NOUNS-8, 2026-09-03): 5 of the shipped rows' extractions grabbed a
  // COMPOUND phrase naming both parties at once — "the upstream and
  // downstream lock-keepers", "The North and South trail coordinators", "Two
  // neighboring orchard operators" — and assigned the whole thing to ONE
  // player, so `dropAmbiguous`'s own rule ("no sentence claims an option
  // belongs to a player who does not own it") would be violated the moment
  // this ships: colouring "the upstream and downstream lock-keepers" as
  // Player A's colour claims Player B's half of that phrase too. Every
  // instance in the corpus was structural (an "X and Y" conjunction, or an
  // explicit "two"/"the two"), never a legitimate single-entity name that
  // happens to contain the word "and" — so this is precise on the corpus
  // measured, not merely plausible.
  // Tested against norm(t), not the raw string: a zero-width character
  // inside "and" ("a​nd") breaks the contiguous match the regex needs, so
  // testing the raw text would let a compound noun through undetected
  // (CodeRabbit, phase 3 review) — the SAME class of bypass the verbatim
  // check above was already fixed against, just unfixed here too.
  const COMPOUND = /\btwo\b|\band\b/i;
  if (all.some((t) => COMPOUND.test(norm(t)))) return false;
  // SAME DEFECT, SUBTLER SHAPE: a PLAIN PLURAL collective noun ("ferry
  // operators", "dairy farmers", "kelp farmers") assigned to exactly one
  // player while the description names both SYMMETRICALLY ("Two neighboring
  // ferry operators share a crossing... Each chooses...") without ever
  // individually distinguishing either one. The COMPOUND check above cannot
  // see this — the noun contains no "and"/"two", is genuinely verbatim,
  // disjoint (the other side is empty) and uncollided — only the
  // description's OWN symmetric framing shows it belongs to neither player
  // over the other. 11 more shipped rows, hand-confirmed 11/11 genuine
  // (0 exceptions among rows this fires on, checked over the full backfill):
  // every "each"/"both" description with exactly one side populated turned
  // out to be this same collective-noun mistake, never a legitimate case
  // where the OTHER player simply has no role noun for unrelated reasons.
  // This MUST live here, not only in `_gen/bank_actor_nouns_merge.ts` — a
  // rule that only the build script enforces is invisible to
  // `scenariobank.test.ts`'s re-screen of the SHIPPED artifact, which calls
  // only this function; reverting the build-script filter would then ship
  // the defect again with every check still green.
  // Same fix as COMPOUND above: tested against descNorm (already computed),
  // not the raw description, for the same zero-width-bypass reason.
  //
  // The looser H5 re-attempt pass (handoff 2026-09-04, over the 645 rows the
  // strict phase-3 pass left noun-free) surfaced TWO more symmetric-framing
  // markers the "each"/"both" test did not cover, both the SAME defect class:
  // a plural collective noun ("orchard keepers", "lock-keepers") assigned to
  // ONE side of a description that names the two parties collectively ("Two
  // neighboring orchard keepers...") and then distinguishes them only
  // POSITIONALLY — "One chooses... the other chooses", or "The first chooses...
  // the second chooses" — rather than with "each"/"both". Found on idx 257 (a
  // new H5 row) and idx 1965 (a PRE-EXISTING phase-3 row the narrower rule had
  // missed). Keyed on the description's framing, not the noun's plurality —
  // matching the phase-3 rule's own positive control (the same collective noun
  // is accepted under a non-symmetric framing) — and, like that rule, scoped to
  // one-sided rows so a legitimate pair of distinct nouns is never touched.
  const onlyOneSide = (a.length > 0) !== (b.length > 0);
  // Positional words are evidence only when they are the grammatical subject
  // of a choice. Merely comparing "the first" and "the second" option (or
  // referring to "the other option") says nothing about how actors are named.
  // Allow a short actor noun phrase ("the first orchard keeper chooses")
  // without crossing punctuation into a later, unrelated choosing clause.
  const oneOtherChoose = /\bone(?:\s+[a-z][a-z'’-]*){0,4}\s+chooses?\b/i.test(descNorm)
    && /\bthe other(?:\s+[a-z][a-z'’-]*){0,4}\s+chooses?\b/i.test(descNorm);
  const firstSecondChoose = /\bthe first(?:\s+[a-z][a-z'’-]*){0,4}\s+chooses?\b/i.test(descNorm)
    && /\bthe second(?:\s+[a-z][a-z'’-]*){0,4}\s+chooses?\b/i.test(descNorm);
  const symmetricFraming = /\b(each|both)\b/i.test(descNorm)
    || oneOtherChoose
    || firstSecondChoose;
  if (onlyOneSide && symmetricFraming) return false;
  return true;
}
