/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * The pre-verified scenario bank — what the desktop shows instead of running a
 * model.
 *
 * WHY A BANK AT ALL. The retrained local 0.6B is excellent on every decidable
 * axis (six-screen defects 5%, gate rejection 1.0%, 1.35s) and still writes an
 * incoherent world about a quarter of the time — a rice farmer with a saffron
 * crop, a coffee roastery that harvests its own beans. That class is invisible
 * to every screen we ship: 178 of 178 defective stories passed all three gates.
 * And it cannot be trained out from here, because the teacher corpus IS cloud
 * output and cloud is 0% defective — the incoherence is generated by the small
 * model, not inherited, so no retrain on cleaner data addresses it.
 *
 * Measured head to head, blind, criteria sealed before generation and picks
 * sealed before the key, paired on identical (game, domain):
 *
 *     bank   0/68 defective        model   25% defective     p = 6.1e-5
 *
 * WHY THIS IS NOT A CHEAT. At rung 3 the story is MEASURABLY independent of the
 * game: an all-zero matrix produces stories indistinguishable from real ones
 * (p=0.115), and varying the game moves output no more than resampling the same
 * game does (p=0.238). That is by design — the solver states every number, so
 * the description is forbidden to. The one property that does depend on the
 * game is the STAKES BAND, and that is what the bank is indexed on. Selection
 * therefore delivers exactly what generation delivered, minus the incoherence.
 *
 * It also costs less: no model in the installer (~378 MB saved) and no
 * inference at display time.
 */
import type { GamePayoffs, SuggestedScenario } from '../types';
import { describeStakes } from './scenarioStakes';

export interface BankEntry {
  /** 0 tiny · 1 modest · 2 substantial · 3 very large — the stakes band. */
  b: number;
  /** The rotation setting this story was written for. */
  d: string;
  s: SuggestedScenario;
}

/** The four bands, matching `stakesHint`'s cuts exactly. */
export function stakesBand(g: GamePayoffs): number {
  const swing = describeStakes(g).swing;
  return swing < 1 ? 0 : swing < 10 ? 1 : swing < 50 ? 2 : 3;
}

/**
 * Pick a story for this game, WITHOUT REPLACEMENT within a session.
 *
 * The naive picker — uniform with replacement inside a cell — returns a
 * previously seen story 20.6% of the time on the second draw and 50.7% on the
 * third, and a previously seen NAME 44.8% of the time, because 214 of 314 cells
 * hold at least two stories sharing a title. The prose underneath is genuinely
 * different (6 of 3,678 within-cell pairs above Jaccard 0.5, none above 0.7),
 * so this is a naming problem rather than a content one — but a reader meeting
 * "Harbour Inspection" three times will not care about the distinction.
 *
 * `seen` is the caller's session memory. Unseen entries are preferred, then
 * unseen NAMES, and only when a cell is exhausted does it fall back — at which
 * point repeating is the honest outcome rather than a bug.
 */
export function pickFromBank(
  bank: BankEntry[],
  g: GamePayoffs,
  domain: string,
  seen: ReadonlySet<string>,
  pick: () => number = Math.random,
): SuggestedScenario | null {
  const band = stakesBand(g);
  const exact = bank.filter((e) => e.d === domain && e.b === band);
  // A cell can be thin or empty. Widen by band first (the domain is what the
  // reader actually sees), then by domain, rather than returning nothing.
  const pool = exact.length ? exact
    : bank.filter((e) => e.d === domain).length ? bank.filter((e) => e.d === domain)
      : bank.filter((e) => e.b === band);
  if (!pool.length) return null;

  const seenNames = new Set([...seen].map((k) => k.split('|')[1]));
  const unseen = pool.filter((e) => !seen.has(bankKey(e)));
  const unseenName = pool.filter((e) => !seenNames.has(e.s.name ?? ''));
  // ORDER MATTERS, and getting it wrong reintroduces the defect this exists to
  // prevent. Preferring "an entry I have not shown" over "a name I have not
  // shown" still returns a repeated TITLE whenever a cell holds two stories
  // under one name — which 214 of 314 real cells do. The first tier therefore
  // requires BOTH; only then does it relax, and it relaxes on the name last,
  // because the title is what a reader recognises.
  const both = unseen.filter((e) => !seenNames.has(e.s.name ?? ''));
  const from = both.length ? both : unseenName.length ? unseenName : unseen.length ? unseen : pool;
  return from[Math.min(Math.floor(pick() * from.length), from.length - 1)].s;
}

/** The session key for an entry the caller has shown. */
export function bankKey(e: BankEntry): string {
  return `${e.d}|${e.s.name}|${(e.s.description ?? '').slice(0, 40)}`;
}
