/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * The pre-verified scenario bank — what the desktop shows instead of running a
 * model.
 *
 * WHY A BANK AT ALL. The retrained local 0.6B is excellent on every decidable
 * axis (six-screen defects 5%, gate rejection 1.0%, 1.35s) and still writes an
 * incoherent world about a quarter of the time — a rice farmer with a saffron
 * crop, a coffee roastery that harvests its own beans. That class is invisible
 * to every screen we ship: 178 of 178 defective stories passed all three gates.
 * And it cannot be trained out from here, because the teacher corpus IS cloud
 * output and cloud is 0% defective — the incoherence is generated by the small
 * model, not inherited, so no retrain on cleaner data addresses it.
 *
 * Measured head to head, blind, criteria sealed before generation and picks
 * sealed before the key, paired on identical (game, domain):
 *
 *     bank   0/68 defective        model   25% defective     p = 6.1e-5
 *
 * WHY THIS IS NOT A CHEAT. At rung 3 the story is MEASURABLY independent of the
 * game: an all-zero matrix produces stories indistinguishable from real ones
 * (p=0.115), and varying the game moves output no more than resampling the same
 * game does (p=0.238). That is by design — the solver states every number, so
 * the description is forbidden to. The one property that does depend on the
 * game is the STAKES BAND, and that is what the bank is indexed on. Selection
 * therefore delivers exactly what generation delivered, minus the incoherence.
 *
 * It also costs less: no model in the installer (~378 MB saved) and no
 * inference at display time.
 */
import type { GamePayoffs, SuggestedScenario } from '../types';
import { describeStakes } from './scenarioStakes';

export interface BankEntry {
  /** 0 tiny · 1 modest · 2 substantial · 3 very large — the stakes band. */
  b: number;
  /** The rotation setting this story was written for. */
  d: string;
  s: SuggestedScenario;
}

/** The four bands, matching `stakesHint`'s cuts exactly. */
export function stakesBand(g: GamePayoffs): number {
  const swing = describeStakes(g).swing;
  return swing < 1 ? 0 : swing < 10 ? 1 : swing < 50 ? 2 : 3;
}

/**
 * Pick a story for this game, WITHOUT REPLACEMENT within a session.
 *
 * The naive picker — uniform with replacement inside a cell — returns a
 * previously seen story 20.6% of the time on the second draw and 50.7% on the
 * third, and a previously seen NAME 44.8% of the time, because 214 of 314 cells
 * hold at least two stories sharing a title. The prose underneath is genuinely
 * different (6 of 3,678 within-cell pairs above Jaccard 0.5, none above 0.7),
 * so this is a naming problem rather than a content one — but a reader meeting
 * "Harbour Inspection" three times will not care about the distinction.
 *
 * WHY "WITHOUT REPLACEMENT" DID NOT HOLD IN PRACTICE, and the fix. The tiers
 * below only ever looked INSIDE one pool, and the pool was the exact
 * (domain, band) cell whenever that cell was non-empty. 34 of 320 cells in the
 * shipped artifact hold exactly ONE distinct name — "lighthouse relief shifts"
 * band 2 is eight rows all titled "Lighthouse Relief Shifts" — so the moment
 * that title was shown, every remaining row in the cell fell to the last tier
 * and the title came back. Measured on the shipped bank with the domain held
 * fixed, which is the condition that isolates the defect: repeated-title rate
 * 29.5% at 5 presses, 60.7% at 10, 80.3% at 20, 90.2% at 40.
 *
 * So a cell that cannot offer an unseen NAME now WIDENS rather than repeating.
 *
 * THE WIDENING LADDER, and why it is ordered this way. The two things a widened
 * pick can lose are the stakes register and the setting:
 *
 *   1. the exact cell — (domain, band)
 *   2. THE SAME BAND, any domain
 *   3. the same domain, any band
 *   4. anything at all
 *
 * Band before domain, because the band is derived from the USER'S OWN MATRIX
 * while the domain is a rotation choice the user never made and cannot see the
 * absence of. A story from the wrong band contradicts the numbers printed
 * beside it — "a modest patch of coppice" against a swing of 120 — which is a
 * mismatch a reader can detect; a story from a different setting is simply a
 * different setting. (This also fixes the reverse defect: an EMPTY exact cell
 * used to widen by DOMAIN first, so a band-3 game in a domain whose band-3 cell
 * was empty was served that domain's band-0 story.)
 *
 * `seen` is the caller's session memory. Note that an unseen NAME implies an
 * unseen ENTRY — `seenNames` is derived from `seen` — so the old middle tier
 * ("unseen name, seen entry") was unreachable and is gone rather than left
 * standing as a check that cannot fire.
 */
export function pickFromBank(
  bank: BankEntry[],
  g: GamePayoffs,
  domain: string,
  seen: ReadonlySet<string>,
  pick: () => number = Math.random,
): SuggestedScenario | null {
  const band = stakesBand(g);
  const ladder: BankEntry[][] = [
    bank.filter((e) => e.d === domain && e.b === band),
    bank.filter((e) => e.b === band),
    bank.filter((e) => e.d === domain),
    bank,
  ];
  const seenNames = new Set([...seen].map((k) => k.split('|')[1]));
  const take = (pool: BankEntry[]) => pool[Math.min(Math.floor(pick() * pool.length), pool.length - 1)].s;

  // A name the reader has not met, as close to the exact cell as one exists.
  for (const pool of ladder) {
    const fresh = pool.filter((e) => !seenNames.has(e.s.name ?? ''));
    if (fresh.length) return take(fresh);
  }
  // Every name in the bank has been shown. Repeating a title is now the honest
  // outcome; at least give the reader prose they have not read.
  for (const pool of ladder) {
    const unseen = pool.filter((e) => !seen.has(bankKey(e)));
    if (unseen.length) return take(unseen);
  }
  for (const pool of ladder) if (pool.length) return take(pool);
  return null;
}

/** The session key for an entry the caller has shown. */
export function bankKey(e: BankEntry): string {
  return `${e.d}|${e.s.name}|${(e.s.description ?? '').slice(0, 40)}`;
}

/**
 * THE GAMES A BANK ROW MUST SURVIVE — the serving condition, written down.
 *
 * `_gen/bank_build.ts` gates each row against the game it was GENERATED for.
 * `pickFromBank` then serves it with the game the USER typed. Every
 * game-dependent rule in `validateScenario` therefore gets a different answer at
 * serve time than it did at build time, and a row can be admitted to the bank
 * and rejected in front of a reader — where the desktop has no model to fall
 * back to and, measured through the real path, the response silently carries no
 * story at all.
 *
 * That is not hypothetical. 19 shipped rows carry rivalry vocabulary ("competing
 * for", "are rivals") and `validateScenario` rejects those on any COMMON-INTEREST
 * matrix, which is the plain pure-coordination game and also the all-zero matrix
 * a user gets by clearing the payoff fields. Reproduced independently by two
 * agents from opposite directions — a 270-game probe sweep and a
 * one-probe-per-conditional-branch sweep — and both found the same 19 and only
 * those 19.
 *
 * So a row must survive EVERY shape it can be served with, and this is that set:
 * one entry per condition the gates actually branch on, read off the code rather
 * than guessed, at three magnitudes because `stakesBand` and the near-tolerances
 * are scale-dependent.
 *
 * NOT BAND-SCOPED, DELIBERATELY. `pickFromBank`'s ladder is band-locked at tiers
 * 1 and 2, so a band-0 game cannot reach a band-3 row until every band-0 name is
 * exhausted — which means an incidence measured on one band says nothing about
 * another (the same 19 rows are 1.50% of presses on a band-3 common-interest
 * game and 0.00% on a band-0 one). Reachability is what matters here, not
 * incidence: tiers 3 and 4 mean ANY row can eventually be served for ANY game,
 * so the screen must ignore bands entirely. Do not "optimise" this by matching
 * the probe's band to the row's.
 *
 * AND A WARNING ABOUT ITS ZEROS. Most of these shapes currently return zero
 * rejections, and that is NOT evidence the artifact is safe on them — it is
 * evidence the corpus never says the things those rules look for
 * (`SHARED_GOAL`, `ABSTRACT_COORD`, `COORD_TALK`, `ANTI_TALK` and `DETERMINES`
 * all have zero vocabulary presence in the bank). The probes earn their keep the
 * day a generation run or a narrowed screen lets that vocabulary back in.
 */
export const SERVE_PROBES: GamePayoffs[] = (() => {
  const shapes: Array<(k: number) => GamePayoffs> = [
    // common interest — both payoffs identical in every cell (rivalry rule)
    (k) => ({ a11: 9 * k, a12: -4 * k, a21: -4 * k, a22: 7 * k, b11: 9 * k, b12: -4 * k, b21: -4 * k, b22: 7 * k }),
    // constant sum, NON-zero total (shared-goal rule) — every cell sums to 10k.
    // A zero total would be the zero-sum shape below rather than a distinct one.
    (k) => ({ a11: 3 * k, a12: -2 * k, a21: -4 * k, a22: 5 * k, b11: 7 * k, b12: 12 * k, b21: 14 * k, b22: 5 * k }),
    // zero sum on the matching diagonal
    (k) => ({ a11: 2 * k, a12: -2 * k, a21: -2 * k, a22: 2 * k, b11: -2 * k, b12: 2 * k, b21: 2 * k, b22: -2 * k }),
    // A indifferent between its OWN actions: a11 === a21 and a12 === a22, so
    // A's two rows pay the same against either column and a whole line is in
    // equilibrium. B stays strict, so exactly one player is indifferent.
    (k) => ({ a11: 5 * k, a12: 2 * k, a21: 5 * k, a22: 2 * k, b11: 1 * k, b12: 4 * k, b21: 3 * k, b22: 0 }),
    // B indifferent between its OWN actions: b11 === b12 and b21 === b22.
    (k) => ({ a11: 1 * k, a12: 4 * k, a21: 3 * k, a22: 0, b11: 5 * k, b12: 5 * k, b21: 2 * k, b22: 2 * k }),
    // dominance for both (dependence-framing rules)
    (k) => ({ a11: 3 * k, a12: 0, a21: 5 * k, a22: 1 * k, b11: 3 * k, b12: 5 * k, b21: 0, b22: 1 * k }),
    // pure equilibria on MATCHING pairs (coordination direction check)
    (k) => ({ a11: 4 * k, a12: 0, a21: 0, a22: 3 * k, b11: 3 * k, b12: 0, b21: 0, b22: 4 * k }),
    // pure equilibria on MISMATCHED pairs (anti-coordination direction check)
    (k) => ({ a11: 0, a12: 4 * k, a21: 3 * k, a22: 0, b11: 0, b12: 3 * k, b21: 4 * k, b22: 0 }),
    // no pure equilibrium at all
    (k) => ({ a11: 2 * k, a12: -1 * k, a21: -1 * k, a22: 1 * k, b11: -2 * k, b12: 1 * k, b21: 1 * k, b22: -1 * k }),
  ];
  const out: GamePayoffs[] = shapes.flatMap((f) => [f(0.1), f(1), f(20)]);
  // BOTH players indifferent — the all-zero matrix a user gets by clearing every
  // field. Scale-free, so it is added once rather than three times.
  out.push({ a11: 0, a12: 0, a21: 0, a22: 0, b11: 0, b12: 0, b21: 0, b22: 0 });
  return out;
})();
