/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * DESKTOP .CJS CONTRACT — the guard for a defect class the whole five-job CI
 * pyramid was blind to.
 *
 * On 2026-08-31, electron-llama.cjs was committed in a state that did not load:
 * a constant had been renamed and five references to the old name survived, one
 * at module top level, so `require()` threw ReferenceError on the first line
 * that mattered. Every job went green. `npm run lint` is `tsc --noEmit`;
 * tsconfig sets `allowJs` without `checkJs`; there is no ESLint in the repo. The
 * root .cjs files — including electron-main.cjs, the app's declared `main` — are
 * type-checked by nothing, linted by nothing and executed by nothing. A module
 * that throws on require bricks the desktop app at launch and ships green.
 *
 * Three checks, because each catches what the others cannot:
 *
 *   1. `node --check` on every root .cjs          — syntax
 *   2. a real `require()` of every root .cjs      — top-level execution, which
 *      is the only thing that catches the actual defect (it was valid syntax)
 *   3. an export-SHAPE assertion on electron-llama.cjs — because loading is not
 *      enough: electron-main.cjs destructures specific names off it, and the
 *      shape changed in 2470029 (activePort became a function; LLAMA_PORT, which
 *      the port is chosen at run time so cannot be a constant, was removed).
 *
 * Every check carries a KNOWN-POSITIVE and a KNOWN-NEGATIVE. The known-positives
 * are generated by MUTATING the real file at test time rather than pasted, so
 * the fixture cannot drift away from the code it guards and is always a genuine
 * instance of the class. A check that cannot fail is not a check: each mutation
 * below is asserted to be caught, and the unmutated file is asserted to pass.
 *
 * `tsx src/desktop.contract.test.ts`, part of `npm test`, CI job `unit`.
 * No Electron, no llama-server, no ports, no network.
 */

import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require_ = createRequire(import.meta.url);
const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const PROBE = join(ROOT, 'src', 'desktop', 'require-probe.cjs');
const LLAMA = join(ROOT, 'electron-llama.cjs');

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

/** Every .cjs at the repo root — discovered, so a new one is covered on sight. */
function rootCjsFiles(): string[] {
  return readdirSync(ROOT).filter((f) => f.endsWith('.cjs')).sort();
}

/** `node --check <file>` — true when it parses. */
function parses(file: string): boolean {
  return spawnSync(process.execPath, ['--check', file], { encoding: 'utf8' }).status === 0;
}

/** Load a .cjs for real (Electron stubbed out). Returns null on success, else the error line. */
function loadFails(file: string): string | null {
  const r = spawnSync(process.execPath, [PROBE, file], { encoding: 'utf8' });
  return r.status === 0 ? null : (r.stdout || r.stderr || '').trim() || 'unknown failure';
}

function scratch(name: string, source: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'nash-cjs-'));
  const p = join(dir, name);
  writeFileSync(p, source);
  return p;
}

/** Mutate the real source, keeping the fixture permanently in sync with the code. */
function mutateLlama(apply: (src: string) => string, label: string): string {
  const original = readFileSync(LLAMA, 'utf8');
  const mutated = apply(original);
  assert(mutated !== original, `mutation "${label}" changed nothing — the anchor it edits has moved`);
  return scratch('electron-llama.cjs', mutated);
}

// ---------------------------------------------------------------------------
// 1. Syntax
// ---------------------------------------------------------------------------
function testEveryRootCjsParses() {
  const files = rootCjsFiles();
  assert(files.length >= 4, `expected the four root .cjs files, found ${files.length}`);
  for (const f of files) {
    assert(parses(join(ROOT, f)), `node --check failed on ${f}`);
  }
  // known-positive: the check must be able to fail
  const broken = scratch('broken.cjs', 'const a = ;\n');
  assert(!parses(broken), 'node --check accepted a syntax error — the parse check is inert');
  // known-negative: and must not fail on a trivially valid file
  assert(parses(scratch('fine.cjs', 'module.exports = { a: 1 };\n')), 'node --check rejected a valid file');
}

// ---------------------------------------------------------------------------
// 2. Top-level execution — the check that would have caught the real defect
// ---------------------------------------------------------------------------
function testEveryRootCjsLoads() {
  for (const f of rootCjsFiles()) {
    const err = loadFails(join(ROOT, f));
    assert(err === null, `require('${f}') threw: ${err}`);
  }

  // KNOWN-POSITIVE, the authentic defect shape: rename the constant's
  // declaration and leave its references behind. One of them is at top level,
  // so require() throws ReferenceError — exactly what shipped green.
  const renamed = mutateLlama(
    (s) => s.replace('const LLAMA_PORT_BASE = 14322;', 'const LLAMA_PORT_RENAMED = 14322;'),
    'rename LLAMA_PORT_BASE',
  );
  const renamedErr = loadFails(renamed);
  assert(renamedErr !== null, 'a module with a dangling constant reference LOADED — the require check is inert');
  assert(
    /ReferenceError/.test(renamedErr),
    `expected ReferenceError from the renamed-constant fixture, got: ${renamedErr}`,
  );

  // KNOWN-POSITIVE: a throw that only happens at top level, nowhere else.
  const throws = mutateLlama((s) => `${s}\nundefinedIdentifierAtTopLevel;\n`, 'top-level throw');
  assert(loadFails(throws) !== null, 'a module that throws at top level LOADED — the require check is inert');

  // KNOWN-NEGATIVE: the unmutated file must load cleanly, or every positive
  // above is meaningless.
  assert(loadFails(LLAMA) === null, 'the real electron-llama.cjs does not load');
}

// ---------------------------------------------------------------------------
// 3. Export shape — electron-main.cjs destructures these names
// ---------------------------------------------------------------------------
type ShapeProblem = string | null;

/** The contract, asserted against a loaded module object. */
function shapeProblem(m: any): ShapeProblem {
  if (typeof m?.startLocalModel !== 'function') return 'startLocalModel is not a function';
  if (typeof m?.stopLocalModel !== 'function') return 'stopLocalModel is not a function';
  // The port is chosen at run time by a bind test, so it CANNOT be a constant.
  // This is the 2470029 change: a getter, not a number.
  if (typeof m?.activePort !== 'function') return 'activePort is not a function';
  if (m.activePort() !== null) return 'activePort() should be null before startLocalModel';
  if ('LLAMA_PORT' in m) return 'LLAMA_PORT is exported again — the port is not a constant';
  if (!Number.isInteger(m?.LLAMA_PORT_BASE)) return 'LLAMA_PORT_BASE is not an integer';
  // server.ts walks upward from 14321; llama-server must never start there.
  if (m.LLAMA_PORT_BASE === 14321) return 'LLAMA_PORT_BASE collides with the Express port';
  if (!Number.isInteger(m?.LLAMA_CTX)) return 'LLAMA_CTX is not an integer';
  for (const fn of ['portFree', 'verifyIsOurs', 'servedContext', 'waitHealthy']) {
    if (typeof m?._internals?.[fn] !== 'function') return `_internals.${fn} is not a function`;
  }
  return null;
}

function testExportShape() {
  const real = require_(LLAMA);
  const problem = shapeProblem(real);
  assert(problem === null, `electron-llama.cjs export shape: ${problem}`);

  // KNOWN-POSITIVES: each mutation must be caught, and by the RIGHT clause.
  const cases: Array<[string, (s: string) => string, RegExp]> = [
    ['activePort dropped', (s) => s.replace('activePort: () => activePort,', ''), /activePort is not a function/],
    ['activePort back to a number', (s) => s.replace('activePort: () => activePort,', 'activePort: 14322,'), /activePort is not a function/],
    ['LLAMA_PORT resurrected', (s) => s.replace('LLAMA_PORT_BASE,', 'LLAMA_PORT_BASE,\n  LLAMA_PORT: 14322,'), /LLAMA_PORT is exported again/],
    ['base collides with Express', (s) => s.replace('const LLAMA_PORT_BASE = 14322;', 'const LLAMA_PORT_BASE = 14321;'), /collides with the Express port/],
    ['an internal goes missing', (s) => s.replace('verifyIsOurs, servedContext', 'servedContext'), /_internals\.verifyIsOurs is not a function/],
  ];
  for (const [label, apply, expected] of cases) {
    const fixture = mutateLlama(apply, label);
    const got = shapeProblem(require_(fixture));
    assert(got !== null, `mutation "${label}" was NOT caught — the shape check is inert for it`);
    assert(expected.test(got), `mutation "${label}" was caught by the wrong clause: ${got}`);
  }
}

// ---------------------------------------------------------------------------
// 4. No tracked file may still consume the removed export
// ---------------------------------------------------------------------------
function consumersOfRemovedExport(files: string[]): string[] {
  const hits: string[] = [];
  for (const f of files) {
    if (f === 'electron-llama.cjs') continue;
    let text: string;
    try { text = readFileSync(join(ROOT, f), 'utf8'); } catch { continue; }
    // `LLAMA_PORT` as a whole word — LLAMA_PORT_BASE must not match.
    if (/\bLLAMA_PORT\b(?!_)/.test(text)) hits.push(f);
  }
  return hits;
}

function testNoStaleConsumers() {
  const tracked = execFileSync('git', ['ls-files'], { cwd: ROOT, encoding: 'utf8' })
    .split('\n')
    .filter((f) => /\.(cjs|mjs|js|ts|tsx|json|yml|yaml)$/.test(f));
  const hits = consumersOfRemovedExport(tracked);
  assert(hits.length === 0, `these tracked files still reference the removed LLAMA_PORT export: ${hits.join(', ')}`);

  // known-positive: the scanner must flag a file that does reference it, and
  // must NOT be fooled by the constant that legitimately remains.
  const bad = scratch('consumer.cjs', "const { LLAMA_PORT } = require('./electron-llama.cjs');\n");
  const good = scratch('ok.cjs', "const { LLAMA_PORT_BASE } = require('./electron-llama.cjs');\n");
  assert(/\bLLAMA_PORT\b(?!_)/.test(readFileSync(bad, 'utf8')), 'the scanner cannot see a real consumer');
  assert(!/\bLLAMA_PORT\b(?!_)/.test(readFileSync(good, 'utf8')), 'the scanner false-positives on LLAMA_PORT_BASE');
}

function runDesktopContractTests() {
  testEveryRootCjsParses();
  testEveryRootCjsLoads();
  testExportShape();
  testNoStaleConsumers();
  console.log('All desktop .cjs contract tests passed.');
}

try {
  runDesktopContractTests();
} catch (err: any) {
  console.error('Desktop .cjs contract failure:');
  console.error(err?.message || err);
  process.exit(1);
}
