/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * DESKTOP .CJS CONTRACT — the guard for a defect class the whole CI pyramid
 * was blind to.
 *
 * On 2026-08-31, on a since-closed branch (PR #52, DMG-bundled local model,
 * never merged to main), a root .cjs file was committed in a state that did
 * not load: a constant had been renamed and five references to the old name
 * survived, one at module top level, so `require()` threw ReferenceError on
 * the first line that mattered. Every CI job went green anyway. `npm run
 * lint` is `tsc --noEmit`; tsconfig sets `allowJs` without `checkJs`; there is
 * no ESLint in the repo. The root .cjs files — including electron-main.cjs,
 * the app's declared `main` — are type-checked by nothing, linted by nothing
 * and executed by nothing. A module that throws on require bricks the desktop
 * app at launch and ships green. That exact file never reached main, but the
 * hole it exposed is a property of every root `.cjs` file, not of the one
 * that happened to be broken — nothing here depends on PR #52's content.
 *
 * Two checks, because each catches what the other cannot:
 *
 *   1. `node --check` on every root .cjs   — syntax
 *   2. a real `require()` of every root .cjs — top-level execution, which is
 *      the only thing that catches the actual defect class (it was valid
 *      syntax: a dangling reference to a renamed identifier)
 *
 * Every check carries a KNOWN-POSITIVE and a KNOWN-NEGATIVE. The known-
 * positives are generated by MUTATING the real file at test time rather than
 * pasted, so the fixture cannot drift away from the code it guards and is
 * always a genuine instance of the class. A check that cannot fail is not a
 * check: each mutation below is asserted to be caught, and the unmutated file
 * is asserted to pass.
 *
 * `tsx src/desktop.contract.test.ts`, part of `npm test`, CI job `unit`.
 * No Electron, no network, no ports bound.
 */

import { spawnSync } from 'node:child_process';
import { mkdtempSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const PROBE = join(ROOT, 'src', 'desktop', 'require-probe.cjs');
const MAIN_CJS = join(ROOT, 'electron-main.cjs');

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

/** Every .cjs at the repo root — discovered, so a new one is covered on sight. */
function rootCjsFiles(): string[] {
  return readdirSync(ROOT).filter((f) => f.endsWith('.cjs')).sort();
}

/** `node --check <file>` — true when it parses. */
function parses(file: string): boolean {
  return spawnSync(process.execPath, ['--check', file], { encoding: 'utf8' }).status === 0;
}

/** Load a .cjs for real (Electron stubbed out). Returns null on success, else the error line. */
function loadFails(file: string): string | null {
  const r = spawnSync(process.execPath, [PROBE, file], { encoding: 'utf8' });
  return r.status === 0 ? null : (r.stdout || r.stderr || '').trim() || 'unknown failure';
}

function scratch(name: string, source: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'nash-cjs-'));
  const p = join(dir, name);
  writeFileSync(p, source);
  return p;
}

/** Mutate the real electron-main.cjs, keeping the fixture permanently in sync with the code. */
function mutateMain(apply: (src: string) => string, label: string): string {
  const original = readFileSync(MAIN_CJS, 'utf8');
  const mutated = apply(original);
  assert(mutated !== original, `mutation "${label}" changed nothing — the anchor it edits has moved`);
  return scratch('electron-main.cjs', mutated);
}

// ---------------------------------------------------------------------------
// 1. Syntax
// ---------------------------------------------------------------------------
function testEveryRootCjsParses() {
  const files = rootCjsFiles();
  assert(files.length >= 1, 'expected at least one root .cjs file, found none');
  for (const f of files) {
    assert(parses(join(ROOT, f)), `node --check failed on ${f}`);
  }
  // known-positive: the check must be able to fail
  const broken = scratch('broken.cjs', 'const a = ;\n');
  assert(!parses(broken), 'node --check accepted a syntax error — the parse check is inert');
  // known-negative: and must not fail on a trivially valid file
  assert(parses(scratch('fine.cjs', 'module.exports = { a: 1 };\n')), 'node --check rejected a valid file');
}

// ---------------------------------------------------------------------------
// 2. Top-level execution — the check that would have caught the real defect
// ---------------------------------------------------------------------------
function testEveryRootCjsLoads() {
  for (const f of rootCjsFiles()) {
    const err = loadFails(join(ROOT, f));
    assert(err === null, `require('${f}') threw: ${err}`);
  }

  // KNOWN-POSITIVE, the authentic defect shape: rename a constant's
  // declaration and leave a reference to the old name behind. electron-main.cjs
  // assigns `gotTheLock` and reads it on the very next (unconditional) line, so
  // renaming only the declaration reproduces exactly what shipped on
  // 2026-08-31 — a dangling reference to a renamed identifier that only a real
  // require() surfaces.
  const renamed = mutateMain(
    (s) => s.replace(
      'const gotTheLock = app.requestSingleInstanceLock();',
      'const gotTheLockRenamed = app.requestSingleInstanceLock();',
    ),
    'rename gotTheLock',
  );
  const renamedErr = loadFails(renamed);
  assert(renamedErr !== null, 'a module with a dangling constant reference LOADED — the require check is inert');
  assert(
    /ReferenceError/.test(renamedErr),
    `expected ReferenceError from the renamed-identifier fixture, got: ${renamedErr}`,
  );

  // KNOWN-POSITIVE: a throw that only happens at top level, nowhere else.
  const throws = mutateMain((s) => `${s}\nundefinedIdentifierAtTopLevel;\n`, 'top-level throw');
  assert(loadFails(throws) !== null, 'a module that throws at top level LOADED — the require check is inert');

  // KNOWN-NEGATIVE: the unmutated file must load cleanly, or every positive
  // above is meaningless.
  assert(loadFails(MAIN_CJS) === null, 'the real electron-main.cjs does not load');
}

function runDesktopContractTests() {
  testEveryRootCjsParses();
  testEveryRootCjsLoads();
  console.log(`All desktop .cjs contract tests passed (${rootCjsFiles().length} root .cjs files covered).`);
}

try {
  runDesktopContractTests();
} catch (err: any) {
  console.error('Desktop .cjs contract failure:');
  console.error(err?.message || err);
  process.exit(1);
}
